import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const read = (path) => readFileSync(resolve(process.cwd(), path), 'utf8')

test('command palette is app-level, uses Cmd/Ctrl+K, and launches common commands', () => {
  const app = read('src/App.vue')
  const store = read('src/stores/uiStore.ts')
  const shortcuts = read('src/utils/keyboardShortcuts.js')
  const modal = read('src/components/modals/CommandPaletteModal.vue')
  const leftPane = read('src/components/layout/WorkspaceLeftPane.vue')

  assert.equal(shortcuts.includes("id: 'command-palette'"), true)
  assert.equal(shortcuts.includes("keys: ['mod', 'k']"), true)
  assert.equal(shortcuts.includes("id: 'sidebar'"), true)
  assert.equal(shortcuts.includes("keys: ['mod', 'b']"), true)
  assert.equal(shortcuts.includes("id: 'settings'"), true)
  assert.equal(shortcuts.includes("keys: ['mod', ',']"), true)
  assert.equal(shortcuts.includes("id: 'keyboard-shortcuts'"), false)
  assert.equal(app.includes('CommandPaletteModal'), true)
  assert.equal(app.includes("matchShortcut(event, 'command-palette')"), true)
  assert.equal(app.includes('appStore.toggleCommandPalette()'), true)
  assert.equal(store.includes('const isCommandPaletteOpen = ref(false)'), true)
  assert.equal(store.includes('function openCommandPalette()'), true)
  assert.equal(store.includes('function closeCommandPalette()'), true)
  assert.equal(store.includes('function toggleCommandPalette()'), true)
  assert.equal(leftPane.includes('appStore.openCommandPalette()'), true)
  assert.equal(leftPane.includes('MagnifyingGlassIcon'), true)
  assert.equal(leftPane.includes('CommandLineIcon'), false)
  assert.equal(modal.includes('Command Palette'), true)
  assert.equal(modal.includes('MagnifyingGlassIcon'), true)
  assert.equal(modal.includes('CommandLineIcon'), true)
  assert.equal(modal.includes('height: min(78vh, 42rem);'), true)
  assert.equal(modal.includes('class="command-palette-scroll min-h-0 flex-1 overflow-y-auto px-3 py-3"'), true)
  assert.equal(modal.includes('class="command-palette-quick-row"'), true)
  assert.equal(modal.includes('class="command-palette-quick-pill"'), true)
  assert.equal(modal.includes('const commonCommandIds = new Set(['), true)
  assert.equal(modal.includes('Open Settings'), true)
  assert.equal(modal.includes('Show Keyboard Shortcuts'), true)
  assert.equal(modal.includes('Toggle the terminal panel.'), true)
  assert.equal(modal.includes("appStore.setSidebarCollapsed(!appStore.isSidebarCollapsed)"), true)
  assert.equal(modal.includes('appStore.openKeyboardShortcuts()'), true)
  assert.equal(modal.includes("window.dispatchEvent(new CustomEvent('inquira:open-dataset-picker'))"), true)
  assert.equal(modal.includes('createConversationFromPalette'), true)
  assert.equal(modal.includes('const groupedConversationSections = computed(() => {'), true)
  assert.equal(modal.includes('v-for="section in groupedConversationSections"'), true)
  assert.equal(modal.includes('command-palette-workspace-header'), true)
  assert.equal(modal.includes('const displayedConversationRows = computed(() => ('), true)
  assert.equal(modal.includes('apiService.v1ListConversations(workspaceId, 200)'), true)
  assert.equal(modal.includes('appStore.isConversationRunning(id)'), true)
  assert.equal(modal.includes('formatCreatedLabel(createdAt)'), true)
  assert.equal(modal.includes('workspaceInitials(section.workspaceName)'), true)
  assert.equal(modal.includes('workspaceInitials(row.workspaceName)'), false)
  assert.equal(modal.includes('class="command-palette-initials"'), false)
  assert.equal(modal.includes('.command-palette-initials'), false)
  assert.equal(modal.includes('appStore.activateWorkspace(row.workspaceId)'), true)
  assert.equal(modal.includes('appStore.fetchConversationTurns({ reset: true, preferLatest: true })'), true)
})
