import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const read = (path) => readFileSync(resolve(process.cwd(), path), 'utf8')

test('native runtime setup supports company Python mirrors proxies and certificate bundles', () => {
  const workspace = read('src/components/modals/tabs/WorkspaceTab.vue')
  const service = read('src/services/runtimeProvisionService.ts')
  const app = read('../app.go')

  assert.match(workspace, /Company Python/)
  assert.match(workspace, /Internal mirror/)
  assert.match(workspace, /Custom CA bundle/)
  assert.match(workspace, /choosePythonExecutable/)
  assert.match(workspace, /chooseCertificateBundle/)
  assert.match(workspace, /type="password"[^>]*v-model="runtimeConfig\.defaultIndex"/)
  assert.match(workspace, /type="password"[^>]*v-model="runtimeConfig\.httpProxy"/)
  assert.match(workspace, /type="password"[^>]*v-model="runtimeConfig\.httpsProxy"/)
  assert.match(workspace, /runtimeProvisionService\.plan/)
  assert.match(workspace, /Runtime settings/)
  assert.match(workspace, /Company-managed setup/)
  assert.match(workspace, /Install recommended runtime/)
  assert.match(workspace, /clearTransientRuntimeConfig/)
  assert.match(workspace, /runtimeProvisionError/)
  assert.match(service, /callWails\('RuntimePlan'/)
  assert.match(service, /callWails\('ChoosePythonExecutable'/)
  assert.match(service, /callWails\('ChooseCertificateBundle'/)
  assert.match(app, /func \(a \*App\) ChoosePythonExecutable/)
  assert.match(app, /func \(a \*App\) ChooseCertificateBundle/)
})

test('runtime setup is staged, cancellable, and reversible from settings', () => {
  const workspace = read('src/components/modals/tabs/WorkspaceTab.vue')
  const service = read('src/services/runtimeProvisionService.ts')
  const app = read('../app.go')
  const provisioner = read('../internal/runtimeprovision/provisioner.go')
  const contract = read('../internal/runtimeprovision/contract/manifest.go')

  assert.match(workspace, /runtimeCancelable/)
  assert.match(workspace, /Roll back/)
  assert.match(workspace, /incompleteSetup/)
  assert.match(workspace, /approvedPythonVersion/)
  assert.match(workspace, /Compatibility manifest/)
  assert.match(service, /callWails\('CancelRuntimeProvisioning'/)
  assert.match(service, /callWails\('RollbackRuntime'/)
  assert.match(app, /func \(a \*App\) CancelRuntimeProvisioning/)
  assert.match(app, /func \(a \*App\) RollbackRuntime/)
  assert.match(provisioner, /data-worker\.staging/)
  assert.match(provisioner, /data-worker\.previous/)
  assert.match(provisioner, /activateStagedEnvironment/)
  assert.match(contract, /ManagedPythonVersion\s+= "3\.12\.13"/)
})

test('runtime setup keeps only safe successful configuration in status', () => {
  const provisioner = read('../internal/runtimeprovision/provisioner.go')
  const config = read('../internal/runtimeprovision/config.go')

  assert.match(config, /type SavedConfig struct/)
  assert.doesNotMatch(config, /type SavedConfig struct \{[^}]*HTTPProxy/s)
  assert.doesNotMatch(config, /type SavedConfig struct \{[^}]*DefaultIndex/s)
  assert.match(provisioner, /Configuration\s+\*SavedConfig/)
  assert.match(provisioner, /saveConfiguration/)
  assert.match(provisioner, /PlanPreview/)
  assert.match(provisioner, /redactProvisionError/)
})

test('runtime maintenance exposes repair reset progress and privacy-safe diagnostics', () => {
  const workspace = read('src/components/modals/tabs/WorkspaceTab.vue')
  const service = read('src/services/runtimeProvisionService.ts')
  const app = read('../app.go')
  const provisioner = read('../internal/runtimeprovision/provisioner.go')

  assert.match(workspace, /Runtime maintenance/)
  assert.match(workspace, /Repair runtime/)
  assert.match(workspace, /Reset runtime/)
  assert.match(workspace, /Export diagnostics/)
  assert.match(workspace, /runtimeProgressPercent/)
  assert.match(workspace, /isRuntimeResetDialogOpen/)
  assert.match(workspace, /never workspace data, file paths, API keys, proxies, or mirror addresses/)
  assert.match(service, /runtime-provision-progress/)
  assert.match(service, /callWails\('RepairRuntime'/)
  assert.match(service, /callWails\('ResetRuntime'/)
  assert.match(service, /callWails\('ExportRuntimeDiagnostics'/)
  assert.match(app, /func \(a \*App\) RepairRuntime/)
  assert.match(app, /func \(a \*App\) ResetRuntime/)
  assert.match(app, /func \(a \*App\) ExportRuntimeDiagnostics/)
  assert.match(provisioner, /func \(p \*Provisioner\) DiagnosticReport/)
  assert.match(provisioner, /workspace data, user paths, proxy or mirror URLs/)
})
