import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'

const chatInputSource = readFileSync(new URL('../src/components/chat/ChatInput.vue', import.meta.url), 'utf8')
const treeViewSource = readFileSync(new URL('../src/components/chat/TurnTreeView.vue', import.meta.url), 'utf8')
const treeActionsSource = readFileSync(new URL('../src/components/chat/TurnTreeNodeActions.vue', import.meta.url), 'utf8')
const graphViewSource = readFileSync(new URL('../src/components/chat/TurnTreeGraphView.vue', import.meta.url), 'utf8')
const sidebarSource = readFileSync(new URL('../src/components/layout/UnifiedSidebar.vue', import.meta.url), 'utf8')
const rightPanelSource = readFileSync(new URL('../src/components/layout/RightPanel.vue', import.meta.url), 'utf8')
const globalTreeSource = readFileSync(new URL('../src/components/layout/sidebar/SidebarGlobalTurnTree.vue', import.meta.url), 'utf8')
const apiServiceSource = readFileSync(new URL('../src/services/apiService.js', import.meta.url), 'utf8')
const storeSource = readFileSync(new URL('../src/stores/appStore.js', import.meta.url), 'utf8')
const turnTreeModalPath = new URL('../src/components/chat/TurnTreeModal.vue', import.meta.url)
const sidebarConversationsPath = new URL('../src/components/layout/sidebar/SidebarConversations.vue', import.meta.url)

test('turn tree is no longer opened from the composer', () => {
  assert.equal(chatInputSource.includes('ShareIcon'), false)
  assert.equal(chatInputSource.includes('QueueListIcon'), false)
  assert.equal(chatInputSource.includes('title="Open turn tree"'), false)
  assert.equal(chatInputSource.includes('<TurnTreeModal'), false)
  assert.equal(existsSync(turnTreeModalPath), false)
  assert.equal(existsSync(sidebarConversationsPath), false)
})

test('turn tree exposes delete and final actions without unsupported moving controls', () => {
  assert.equal(treeActionsSource.includes("{ id: 'delete', label: 'Delete' }"), true)
  assert.equal(treeActionsSource.includes("action === 'mark-final'"), true)
  assert.equal(treeActionsSource.includes("action === 'move-to'"), false)
  assert.equal(treeActionsSource.includes("action === 'move-up'"), false)
  assert.equal(treeActionsSource.includes("action === 'move-down'"), false)
  assert.equal(globalTreeSource.includes('Delete Turn and Replies'), true)
  assert.equal(globalTreeSource.includes('Delete this turn and all replies below it?'), true)
  assert.equal(treeActionsSource.includes("'delete-turn'"), true)
  assert.equal(treeActionsSource.includes("'move-turn'"), false)
  assert.equal(treeActionsSource.includes("'reorder-turns'"), false)
  assert.equal(treeActionsSource.includes('window.prompt'), false)
  assert.equal(treeActionsSource.includes('conversationId'), true)
})

test('frontend API and store expose turn edit and workspace tree calls', () => {
  assert.equal(apiServiceSource.includes('async v1GetWorkspaceTurnTree(workspaceId)'), true)
  assert.equal(apiServiceSource.includes('async v1DeleteTurn(conversationId, turnId)'), true)
  assert.equal(apiServiceSource.includes('async v1MoveTurn(conversationId, turnId, parentTurnId)'), true)
  assert.equal(apiServiceSource.includes('async v1ReorderTurns(conversationId, parentTurnId, turnIds)'), true)
  assert.equal(storeSource.includes('async function loadWorkspaceTurnTree'), true)
  assert.equal(storeSource.includes('async function deleteTurn(turnId, conversationId = activeConversationId.value)'), true)
  assert.equal(storeSource.includes('async function moveTurn(turnId, parentTurnId, conversationId = activeConversationId.value)'), false)
  assert.equal(storeSource.includes('async function reorderTurnSiblings(parentTurnId, turnIds, conversationId = activeConversationId.value)'), false)
})

test('global tree lives in the dedicated page and opens turns', () => {
  assert.equal(sidebarSource.includes('openConversationTree'), true)
  assert.equal(sidebarSource.includes("appStore.activeTab === 'conversation-tree'"), true)
  assert.equal(sidebarSource.includes('SidebarGlobalTurnTree'), false)
  assert.equal(sidebarSource.includes('SidebarConversations'), false)
  assert.equal(sidebarSource.includes('conversationBadgeLabel(index, appStore.conversations.length)'), true)
  assert.equal(rightPanelSource.includes("appStore.activeTab === 'conversation-tree'"), true)
  assert.equal(rightPanelSource.includes('<SidebarGlobalTurnTree variant="page" />'), true)
  assert.equal(globalTreeSource.includes('TurnTreeView'), true)
  assert.equal(globalTreeSource.includes('TurnTreeGraphView'), true)
  assert.equal(globalTreeSource.includes('inquira.conversation-tree.view'), true)
  assert.equal(graphViewSource.includes('TurnTreeNodeActions'), true)
  assert.equal(globalTreeSource.includes('appStore.loadWorkspaceTurnTree()'), true)
  assert.equal(globalTreeSource.includes("appStore.setActiveTab('workspace')"), true)
  assert.equal(globalTreeSource.includes('appStore.loadActiveTurnRelations(targetTurnId)'), true)
  assert.equal(globalTreeSource.includes('appStore.markTurnFinal(payload?.turnId, payload?.conversationId)'), true)
  assert.equal(globalTreeSource.includes('appStore.deleteTurn(payload?.turnId, payload?.conversationId)'), true)
})
