import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

function readWorkspaceTab() {
  return readFileSync(
    resolve(process.cwd(), 'src/components/modals/tabs/WorkspaceTab.vue'),
    'utf-8',
  )
}

test('workspace setup uses name context and data steps', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes("{ id: 1, label: 'Name' }"), true)
  assert.equal(source.includes("{ id: 2, label: 'Context' }"), true)
  assert.equal(source.includes("{ id: 3, label: 'Data' }"), true)
  assert.equal(source.includes("{ id: 3, label: 'Generate schema' }"), false)
  assert.equal(source.includes('<!-- Step 3: Generate schema -->'), false)
  assert.equal(source.includes('setupStep.value = 3'), true)
  assert.equal(source.includes('@click="skipWorkspaceContext()"'), true)
  assert.equal(source.includes('@click="saveWorkspaceContextAndContinue()"'), true)
  assert.equal(source.includes('class="btn-secondary px-5 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-60"'), true)
  assert.equal(source.includes(':disabled="isSavingWorkspaceIdentity || !setupWorkspaceContext.trim()"'), true)
})

test('workspace dataset view is the only schema management surface', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes('Retry schema generation'), false)
  assert.equal(source.includes('Add at least one dataset before generating schemas.'), false)
  assert.equal(source.includes('@click="generateWorkspaceSchemas"'), false)
  assert.equal(source.includes('Schema generation starts automatically after import.'), false)
})

test('workspace dataset import action is labeled as a primary import datasets action', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes('>Import datasets</span>'), true)
  assert.equal(source.includes('+ Add datasets'), false)
})

test('workspace datasets section uses prominent primary import actions in header and empty state', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes('data-testid="workspace-import-datasets-header"'), true)
  assert.equal(source.includes('data-testid="workspace-import-datasets-empty"'), true)
  assert.equal(source.includes('class="btn-primary px-4 py-2 text-sm'), true)
  assert.equal(source.includes('class="w-full rounded-lg bg-[var(--color-base-soft)] px-4 py-3 text-center text-sm text-[var(--color-text-muted)] transition-all hover:bg-[var(--color-accent-soft)] hover:text-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-60"'), false)
})

test('workspace dataset rows show inline schema status and row-level regenerate control', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes('title="Regenerate schema"'), true)
  assert.equal(source.includes('title="Refresh dataset"'), false)
  assert.equal(source.includes('function datasetSchemaStatusLabel(dataset) {'), true)
  assert.equal(source.includes('function datasetSchemaStatusBadgeClass(dataset) {'), true)
  assert.equal(source.includes('schema_status: String(item?.schema_status || \'queued\')'), true)
  assert.equal(source.includes('{{ datasetSchemaStatusLabel(dataset) }}'), true)
})

test('workspace dataset schema regenerate requires confirmation before enqueueing', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes('isSchemaRegenerateDialogOpen'), true)
  assert.equal(source.includes('schemaRegenerateDialogMessage'), true)
  assert.equal(source.includes('@click="requestRegenerateDatasetSchema(dataset)"'), true)
  assert.equal(source.includes('@click="refreshDatasetSchema(dataset)"'), false)
  assert.equal(source.includes('@confirm="confirmRegenerateDatasetSchema"'), true)
  assert.equal(source.includes('Regenerated schema may differ from the current version because it is generated by the LLM.'), true)
  assert.equal(source.includes('apiService.v1EnqueueDatasetSchemaRegeneration('), true)
})

test('workspace dataset flow relies on persisted schema status instead of a local schema generation step', () => {
  const source = readWorkspaceTab()

  assert.equal(source.includes('const schemaGenerationStatuses = ref({})'), false)
  assert.equal(source.includes('const isGeneratingWorkspaceSchemas = ref(false)'), false)
  assert.equal(source.includes('async function generateWorkspaceSchemas('), false)
  assert.equal(source.includes('autoStart: true'), false)
  assert.equal(source.includes('function syncDatasetSchemaPolling() {'), true)
  assert.equal(source.includes('setInterval(async () => {'), true)
})
