/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Inquira
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type AnalyzeRequestConversationId = string | null;

export type AnalyzeRequestContext = string | null;

export type AnalyzeRequestTableName = string | null;

export type AnalyzeRequestActiveSchemaAnyOf = { [key: string]: unknown };

export type AnalyzeRequestActiveSchema = AnalyzeRequestActiveSchemaAnyOf | null;

export type AnalyzeRequestApiKey = string | null;

/**
 * Analyze input payload bound to workspace+conversation.
 */
export interface AnalyzeRequest {
  workspace_id: string;
  conversation_id?: AnalyzeRequestConversationId;
  /** @minLength 1 */
  question: string;
  current_code?: string;
  model?: string;
  context?: AnalyzeRequestContext;
  table_name?: AnalyzeRequestTableName;
  active_schema?: AnalyzeRequestActiveSchema;
  api_key?: AnalyzeRequestApiKey;
}

/**
 * Analyze output payload with persistence references.
 */
export interface AnalyzeResponse {
  conversation_id: string;
  turn_id: string;
  is_safe: boolean;
  is_relevant: boolean;
  code: string;
  explanation: string;
}

export interface ApiKeyUpdateRequest {
  /** @minLength 1 */
  api_key: string;
}

/**
 * Authenticated user metadata returned to frontend.
 */
export interface AuthUserResponse {
  user_id: string;
  username: string;
  plan: string;
}

export type BrowserDatasetSyncRequestColumnsItem = { [key: string]: unknown };

export type BrowserDatasetSyncRequestRowCount = number | null;

/**
 * Sync browser-loaded table metadata into workspace dataset catalog.
 */
export interface BrowserDatasetSyncRequest {
  /** @minLength 1 */
  table_name: string;
  columns?: BrowserDatasetSyncRequestColumnsItem[];
  row_count?: BrowserDatasetSyncRequestRowCount;
  allow_sample_values?: boolean;
}

export type ConversationCreateRequestTitle = string | null;

/**
 * Conversation create payload.
 */
export interface ConversationCreateRequest {
  title?: ConversationCreateRequestTitle;
}

/**
 * Conversation list response.
 */
export interface ConversationListResponse {
  conversations: ConversationResponse[];
}

export type ConversationResponseLastTurnAt = string | null;

/**
 * Conversation response.
 */
export interface ConversationResponse {
  id: string;
  workspace_id: string;
  title: string;
  last_turn_at: ConversationResponseLastTurnAt;
  created_at: string;
  updated_at: string;
}

export type ConversationUpdateRequestTitle = string | null;

/**
 * Conversation update payload.
 */
export interface ConversationUpdateRequest {
  title?: ConversationUpdateRequestTitle;
}

/**
 * Add dataset payload using a local source file path.
 */
export interface DatasetAddRequest {
  /** @minLength 1 */
  source_path: string;
}

/**
 * List datasets response.
 */
export interface DatasetListResponse {
  datasets: DatasetResponse[];
}

export type DatasetPreviewResponseDataItem = { [key: string]: unknown };

export interface DatasetPreviewResponse {
  table_name: string;
  sample_type: string;
  row_count: number;
  data: DatasetPreviewResponseDataItem[];
}

export type DatasetResponseRowCount = number | null;

export type DatasetResponseFileType = string | null;

/**
 * Workspace dataset response.
 */
export interface DatasetResponse {
  id: number;
  workspace_id: string;
  source_path: string;
  table_name: string;
  row_count: DatasetResponseRowCount;
  file_type: DatasetResponseFileType;
  created_at: string;
  updated_at: string;
}

export type DatasetSchemaResponseColumnsItem = { [key: string]: unknown };

export interface DatasetSchemaResponse {
  table_name: string;
  context?: string;
  columns: DatasetSchemaResponseColumnsItem[];
}

export interface ExecuteRequest {
  /** Python code to execute */
  code: string;
  /**
   * Max execution time in seconds
   * @minimum 1
   * @maximum 300
   */
  timeout?: number;
}

export type ExecuteResponseError = string | null;

export type ExecuteResponseResult = unknown | null;

export type ExecuteResponseResultType = string | null;

export interface ExecuteResponse {
  success: boolean;
  stdout?: string;
  stderr?: string;
  has_stdout?: boolean;
  has_stderr?: boolean;
  error?: ExecuteResponseError;
  result?: ExecuteResponseResult;
  result_type?: ExecuteResponseResultType;
  result_kind?: string;
  result_name?: string | null;
}

export interface GeminiTestRequest {
  /** Google Gemini API key to test */
  api_key: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Login payload.
 */
export interface LoginRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 6
   * @maxLength 128
   */
  password: string;
}

/**
 * Simple message response.
 */
export interface MessageResponse {
  message: string;
}

export type PreferencesResponseActiveWorkspaceId = string | null;

export type PreferencesResponseActiveDatasetPath = string | null;

export type PreferencesResponseActiveTableName = string | null;

export interface PreferencesResponse {
  selected_model?: string;
  available_models?: string[];
  schema_context?: string;
  allow_schema_sample_values?: boolean;
  chat_overlay_width?: number;
  is_sidebar_collapsed?: boolean;
  hide_shortcuts_modal?: boolean;
  active_workspace_id?: PreferencesResponseActiveWorkspaceId;
  active_dataset_path?: PreferencesResponseActiveDatasetPath;
  active_table_name?: PreferencesResponseActiveTableName;
  api_key_present?: boolean;
}

export type PreferencesUpdateRequestSelectedModel = string | null;

export type PreferencesUpdateRequestSchemaContext = string | null;

export type PreferencesUpdateRequestAllowSchemaSampleValues = boolean | null;

export type PreferencesUpdateRequestChatOverlayWidth = number | null;

export type PreferencesUpdateRequestIsSidebarCollapsed = boolean | null;

export type PreferencesUpdateRequestHideShortcutsModal = boolean | null;

export type PreferencesUpdateRequestActiveWorkspaceId = string | null;

export type PreferencesUpdateRequestActiveDatasetPath = string | null;

export type PreferencesUpdateRequestActiveTableName = string | null;

export interface PreferencesUpdateRequest {
  selected_model?: PreferencesUpdateRequestSelectedModel;
  schema_context?: PreferencesUpdateRequestSchemaContext;
  allow_schema_sample_values?: PreferencesUpdateRequestAllowSchemaSampleValues;
  chat_overlay_width?: PreferencesUpdateRequestChatOverlayWidth;
  is_sidebar_collapsed?: PreferencesUpdateRequestIsSidebarCollapsed;
  hide_shortcuts_modal?: PreferencesUpdateRequestHideShortcutsModal;
  active_workspace_id?: PreferencesUpdateRequestActiveWorkspaceId;
  active_dataset_path?: PreferencesUpdateRequestActiveDatasetPath;
  active_table_name?: PreferencesUpdateRequestActiveTableName;
}

/**
 * Register payload.
 */
export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 6
   * @maxLength 128
   */
  password: string;
}

export type SaveSchemaRequestColumnsItem = { [key: string]: unknown };

export interface SaveSchemaRequest {
  context?: string;
  columns: SaveSchemaRequestColumnsItem[];
}

export type SchemaListResponseSchemasItem = { [key: string]: unknown };

export interface SchemaListResponse {
  schemas: SchemaListResponseSchemasItem[];
}

export type TurnPageResponseNextCursor = string | null;

/**
 * Paginated turn response.
 */
export interface TurnPageResponse {
  turns: TurnResponse[];
  next_cursor: TurnPageResponseNextCursor;
}

export type TurnResponseToolEventsAnyOfItem = { [key: string]: unknown };

export type TurnResponseToolEvents = TurnResponseToolEventsAnyOfItem[] | null;

export type TurnResponseMetadataAnyOf = { [key: string]: unknown };

export type TurnResponseMetadata = TurnResponseMetadataAnyOf | null;

export type TurnResponseCodeSnapshot = string | null;

/**
 * Turn response entry.
 */
export interface TurnResponse {
  id: string;
  seq_no: number;
  user_text: string;
  assistant_text: string;
  tool_events: TurnResponseToolEvents;
  metadata: TurnResponseMetadata;
  code_snapshot: TurnResponseCodeSnapshot;
  created_at: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

/**
 * Workspace creation payload.
 */
export interface WorkspaceCreateRequest {
  /**
   * @minLength 1
   * @maxLength 120
   */
  name: string;
}

/**
 * List active deletion jobs response.
 */
export interface WorkspaceDeletionJobListResponse {
  jobs: WorkspaceDeletionJobResponse[];
}

export type WorkspaceDeletionJobResponseErrorMessage = string | null;

/**
 * Workspace deletion job status payload.
 */
export interface WorkspaceDeletionJobResponse {
  job_id: string;
  workspace_id: string;
  status: string;
  error_message?: WorkspaceDeletionJobResponseErrorMessage;
  created_at: string;
  updated_at: string;
}

/**
 * List workspaces response.
 */
export interface WorkspaceListResponse {
  workspaces: WorkspaceResponse[];
}

export interface WorkspacePathsResponse {
  workspace_id: string;
  workspace_dir: string;
  duckdb_path: string;
}

/**
 * Workspace response payload.
 */
export interface WorkspaceResponse {
  id: string;
  name: string;
  is_active: boolean;
  duckdb_path: string;
  created_at: string;
  updated_at: string;
}

export type ListConversationsApiV1WorkspacesWorkspaceIdConversationsGetParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type ListTurnsApiV1ConversationsConversationIdTurnsGetParams = {
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
before?: string | null;
};

export type ResetEverythingApiV1AdminResetPostParams = {
token: string;
};

export type GetWorkspaceDatasetPreviewApiV1WorkspacesWorkspaceIdDatasetsTableNamePreviewGetParams = {
/**
 * @pattern ^(random|first)$
 */
sample_type?: string;
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
};

export const getInquira = () => {
/**
 * Register a new user and immediately issue login session cookie.
 * @summary Register User
 */
const registerUserApiV1AuthRegisterPost = <TData = AxiosResponse<AuthUserResponse>>(
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/register`,
      registerRequest,options
    );
  }

/**
 * Login user and issue session cookie.
 * @summary Login User
 */
const loginUserApiV1AuthLoginPost = <TData = AxiosResponse<AuthUserResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }

/**
 * Return authenticated user profile and plan for UI rendering.
 * @summary Get Current User Profile
 */
const getCurrentUserProfileApiV1AuthMeGet = <TData = AxiosResponse<AuthUserResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * Logout user by deleting current v1 session token and clearing cookie.
 * @summary Logout User
 */
const logoutUserApiV1AuthLogoutPost = <TData = AxiosResponse<MessageResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/logout`,undefined,options
    );
  }

/**
 * List all workspaces for the authenticated user.
 * @summary List Workspaces
 */
const listWorkspacesApiV1WorkspacesGet = <TData = AxiosResponse<WorkspaceListResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces`,options
    );
  }

/**
 * Create a workspace for the authenticated user.
 * @summary Create Workspace
 */
const createWorkspaceApiV1WorkspacesPost = <TData = AxiosResponse<WorkspaceResponse>>(
    workspaceCreateRequest: WorkspaceCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workspaces`,
      workspaceCreateRequest,options
    );
  }

/**
 * Set the active workspace for the authenticated user.
 * @summary Activate Workspace
 */
const activateWorkspaceApiV1WorkspacesWorkspaceIdActivatePut = <TData = AxiosResponse<WorkspaceResponse>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/workspaces/${workspaceId}/activate`,undefined,options
    );
  }

/**
 * Queue async workspace deletion and return job id for polling.
 * @summary Delete Workspace
 */
const deleteWorkspaceApiV1WorkspacesWorkspaceIdDelete = <TData = AxiosResponse<WorkspaceDeletionJobResponse>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/workspaces/${workspaceId}`,options
    );
  }

/**
 * List active workspace deletion jobs for the current user.
 * @summary List Workspace Deletions
 */
const listWorkspaceDeletionsApiV1WorkspacesDeletionsGet = <TData = AxiosResponse<WorkspaceDeletionJobListResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/deletions`,options
    );
  }

/**
 * Get one workspace deletion job status by id.
 * @summary Get Workspace Deletion
 */
const getWorkspaceDeletionApiV1WorkspacesDeletionsJobIdGet = <TData = AxiosResponse<WorkspaceDeletionJobResponse>>(
    jobId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/deletions/${jobId}`,options
    );
  }

/**
 * @summary Get Preferences
 */
const getPreferencesApiV1PreferencesGet = <TData = AxiosResponse<PreferencesResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/preferences`,options
    );
  }

/**
 * @summary Update Preferences
 */
const updatePreferencesApiV1PreferencesPut = <TData = AxiosResponse<PreferencesResponse>>(
    preferencesUpdateRequest: PreferencesUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/preferences`,
      preferencesUpdateRequest,options
    );
  }

/**
 * @summary Set Api Key
 */
const setApiKeyApiV1PreferencesApiKeyPut = <TData = AxiosResponse<MessageResponse>>(
    apiKeyUpdateRequest: ApiKeyUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/preferences/api-key`,
      apiKeyUpdateRequest,options
    );
  }

/**
 * @summary Delete Api Key
 */
const deleteApiKeyApiV1PreferencesApiKeyDelete = <TData = AxiosResponse<MessageResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/preferences/api-key`,options
    );
  }

/**
 * List datasets inside one workspace.
 * @summary List Workspace Datasets
 */
const listWorkspaceDatasetsApiV1WorkspacesWorkspaceIdDatasetsGet = <TData = AxiosResponse<DatasetListResponse>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/${workspaceId}/datasets`,options
    );
  }

/**
 * Add or refresh a dataset in the workspace DuckDB.
 * @summary Add Workspace Dataset
 */
const addWorkspaceDatasetApiV1WorkspacesWorkspaceIdDatasetsPost = <TData = AxiosResponse<DatasetResponse>>(
    workspaceId: string,
    datasetAddRequest: DatasetAddRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workspaces/${workspaceId}/datasets`,
      datasetAddRequest,options
    );
  }

/**
 * Sync browser-loaded table into workspace dataset catalog/schema metadata.
 * @summary Sync Browser Workspace Dataset
 */
const syncBrowserWorkspaceDatasetApiV1WorkspacesWorkspaceIdDatasetsBrowserSyncPost = <TData = AxiosResponse<DatasetResponse>>(
    workspaceId: string,
    browserDatasetSyncRequest: BrowserDatasetSyncRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workspaces/${workspaceId}/datasets/browser-sync`,
      browserDatasetSyncRequest,options
    );
  }

/**
 * Create conversation under a workspace.
 * @summary Create Conversation
 */
const createConversationApiV1WorkspacesWorkspaceIdConversationsPost = <TData = AxiosResponse<ConversationResponse>>(
    workspaceId: string,
    conversationCreateRequest: ConversationCreateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workspaces/${workspaceId}/conversations`,
      conversationCreateRequest,options
    );
  }

/**
 * List workspace conversations ordered by recency.
 * @summary List Conversations
 */
const listConversationsApiV1WorkspacesWorkspaceIdConversationsGet = <TData = AxiosResponse<ConversationListResponse>>(
    workspaceId: string,
    params?: ListConversationsApiV1WorkspacesWorkspaceIdConversationsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/${workspaceId}/conversations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Delete all turns while keeping conversation.
 * @summary Clear Conversation
 */
const clearConversationApiV1ConversationsConversationIdClearPost = <TData = AxiosResponse<MessageResponse>>(
    conversationId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/conversations/${conversationId}/clear`,undefined,options
    );
  }

/**
 * Delete conversation and all turns.
 * @summary Delete Conversation
 */
const deleteConversationApiV1ConversationsConversationIdDelete = <TData = AxiosResponse<MessageResponse>>(
    conversationId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/conversations/${conversationId}`,options
    );
  }

/**
 * Update conversation title.
 * @summary Patch Conversation
 */
const patchConversationApiV1ConversationsConversationIdPatch = <TData = AxiosResponse<ConversationResponse>>(
    conversationId: string,
    conversationUpdateRequest: ConversationUpdateRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/conversations/${conversationId}`,
      conversationUpdateRequest,options
    );
  }

/**
 * List turns using cursor pagination.
 * @summary List Turns
 */
const listTurnsApiV1ConversationsConversationIdTurnsGet = <TData = AxiosResponse<TurnPageResponse>>(
    conversationId: string,
    params?: ListTurnsApiV1ConversationsConversationIdTurnsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/conversations/${conversationId}/turns`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Run analysis in workspace scope and persist a turn.
 * @summary Analyze
 */
const analyzeApiV1ChatAnalyzePost = <TData = AxiosResponse<AnalyzeResponse>>(
    analyzeRequest: AnalyzeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/chat/analyze`,
      analyzeRequest,options
    );
  }

/**
 * Stream analysis events using SSE for real-time UI updates.
 * @summary Stream Analyze
 */
const streamAnalyzeApiV1ChatStreamPost = <TData = AxiosResponse<unknown>>(
    analyzeRequest: AnalyzeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/chat/stream`,
      analyzeRequest,options
    );
  }

/**
 * One-time destructive reset for legacy/users/schema data.

Requires:
  - INQUIRA_ENABLE_RESET=1
  - token matching INQUIRA_RESET_TOKEN
 * @summary Reset Everything
 */
const resetEverythingApiV1AdminResetPost = <TData = AxiosResponse<MessageResponse>>(
    params: ResetEverythingApiV1AdminResetPostParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/reset`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Validate a Gemini key by issuing a lightweight test request.
 * @summary Test Gemini Api Key
 */
const testGeminiApiKeyApiV1AdminTestGeminiPost = <TData = AxiosResponse<unknown>>(
    geminiTestRequest: GeminiTestRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/test-gemini`,
      geminiTestRequest,options
    );
  }

/**
 * @summary Get Workspace Paths
 */
const getWorkspacePathsApiV1WorkspacesWorkspaceIdPathsGet = <TData = AxiosResponse<WorkspacePathsResponse>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/${workspaceId}/paths`,options
    );
  }

/**
 * @summary Execute Workspace Code
 */
const executeWorkspaceCodeApiV1WorkspacesWorkspaceIdExecutePost = <TData = AxiosResponse<ExecuteResponse>>(
    workspaceId: string,
    executeRequest: ExecuteRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workspaces/${workspaceId}/execute`,
      executeRequest,options
    );
  }

/**
 * @summary Get Workspace Dataset Schema
 */
const getWorkspaceDatasetSchemaApiV1WorkspacesWorkspaceIdDatasetsTableNameSchemaGet = <TData = AxiosResponse<DatasetSchemaResponse>>(
    workspaceId: string,
    tableName: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/${workspaceId}/datasets/${tableName}/schema`,options
    );
  }

/**
 * @summary Save Workspace Dataset Schema
 */
const saveWorkspaceDatasetSchemaApiV1WorkspacesWorkspaceIdDatasetsTableNameSchemaPost = <TData = AxiosResponse<DatasetSchemaResponse>>(
    workspaceId: string,
    tableName: string,
    saveSchemaRequest: SaveSchemaRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/workspaces/${workspaceId}/datasets/${tableName}/schema`,
      saveSchemaRequest,options
    );
  }

/**
 * @summary Get Workspace Dataset Preview
 */
const getWorkspaceDatasetPreviewApiV1WorkspacesWorkspaceIdDatasetsTableNamePreviewGet = <TData = AxiosResponse<DatasetPreviewResponse>>(
    workspaceId: string,
    tableName: string,
    params?: GetWorkspaceDatasetPreviewApiV1WorkspacesWorkspaceIdDatasetsTableNamePreviewGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/${workspaceId}/datasets/${tableName}/preview`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary List Workspace Schemas
 */
const listWorkspaceSchemasApiV1WorkspacesWorkspaceIdSchemasGet = <TData = AxiosResponse<SchemaListResponse>>(
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/workspaces/${workspaceId}/schemas`,options
    );
  }

/**
 * Root endpoint to check if API is running
 * @summary Root
 */
const rootGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

return {registerUserApiV1AuthRegisterPost,loginUserApiV1AuthLoginPost,getCurrentUserProfileApiV1AuthMeGet,logoutUserApiV1AuthLogoutPost,listWorkspacesApiV1WorkspacesGet,createWorkspaceApiV1WorkspacesPost,activateWorkspaceApiV1WorkspacesWorkspaceIdActivatePut,deleteWorkspaceApiV1WorkspacesWorkspaceIdDelete,listWorkspaceDeletionsApiV1WorkspacesDeletionsGet,getWorkspaceDeletionApiV1WorkspacesDeletionsJobIdGet,getPreferencesApiV1PreferencesGet,updatePreferencesApiV1PreferencesPut,setApiKeyApiV1PreferencesApiKeyPut,deleteApiKeyApiV1PreferencesApiKeyDelete,listWorkspaceDatasetsApiV1WorkspacesWorkspaceIdDatasetsGet,addWorkspaceDatasetApiV1WorkspacesWorkspaceIdDatasetsPost,syncBrowserWorkspaceDatasetApiV1WorkspacesWorkspaceIdDatasetsBrowserSyncPost,createConversationApiV1WorkspacesWorkspaceIdConversationsPost,listConversationsApiV1WorkspacesWorkspaceIdConversationsGet,clearConversationApiV1ConversationsConversationIdClearPost,deleteConversationApiV1ConversationsConversationIdDelete,patchConversationApiV1ConversationsConversationIdPatch,listTurnsApiV1ConversationsConversationIdTurnsGet,analyzeApiV1ChatAnalyzePost,streamAnalyzeApiV1ChatStreamPost,resetEverythingApiV1AdminResetPost,testGeminiApiKeyApiV1AdminTestGeminiPost,getWorkspacePathsApiV1WorkspacesWorkspaceIdPathsGet,executeWorkspaceCodeApiV1WorkspacesWorkspaceIdExecutePost,getWorkspaceDatasetSchemaApiV1WorkspacesWorkspaceIdDatasetsTableNameSchemaGet,saveWorkspaceDatasetSchemaApiV1WorkspacesWorkspaceIdDatasetsTableNameSchemaPost,getWorkspaceDatasetPreviewApiV1WorkspacesWorkspaceIdDatasetsTableNamePreviewGet,listWorkspaceSchemasApiV1WorkspacesWorkspaceIdSchemasGet,rootGet}};
export type RegisterUserApiV1AuthRegisterPostResult = AxiosResponse<AuthUserResponse>
export type LoginUserApiV1AuthLoginPostResult = AxiosResponse<AuthUserResponse>
export type GetCurrentUserProfileApiV1AuthMeGetResult = AxiosResponse<AuthUserResponse>
export type LogoutUserApiV1AuthLogoutPostResult = AxiosResponse<MessageResponse>
export type ListWorkspacesApiV1WorkspacesGetResult = AxiosResponse<WorkspaceListResponse>
export type CreateWorkspaceApiV1WorkspacesPostResult = AxiosResponse<WorkspaceResponse>
export type ActivateWorkspaceApiV1WorkspacesWorkspaceIdActivatePutResult = AxiosResponse<WorkspaceResponse>
export type DeleteWorkspaceApiV1WorkspacesWorkspaceIdDeleteResult = AxiosResponse<WorkspaceDeletionJobResponse>
export type ListWorkspaceDeletionsApiV1WorkspacesDeletionsGetResult = AxiosResponse<WorkspaceDeletionJobListResponse>
export type GetWorkspaceDeletionApiV1WorkspacesDeletionsJobIdGetResult = AxiosResponse<WorkspaceDeletionJobResponse>
export type GetPreferencesApiV1PreferencesGetResult = AxiosResponse<PreferencesResponse>
export type UpdatePreferencesApiV1PreferencesPutResult = AxiosResponse<PreferencesResponse>
export type SetApiKeyApiV1PreferencesApiKeyPutResult = AxiosResponse<MessageResponse>
export type DeleteApiKeyApiV1PreferencesApiKeyDeleteResult = AxiosResponse<MessageResponse>
export type ListWorkspaceDatasetsApiV1WorkspacesWorkspaceIdDatasetsGetResult = AxiosResponse<DatasetListResponse>
export type AddWorkspaceDatasetApiV1WorkspacesWorkspaceIdDatasetsPostResult = AxiosResponse<DatasetResponse>
export type SyncBrowserWorkspaceDatasetApiV1WorkspacesWorkspaceIdDatasetsBrowserSyncPostResult = AxiosResponse<DatasetResponse>
export type CreateConversationApiV1WorkspacesWorkspaceIdConversationsPostResult = AxiosResponse<ConversationResponse>
export type ListConversationsApiV1WorkspacesWorkspaceIdConversationsGetResult = AxiosResponse<ConversationListResponse>
export type ClearConversationApiV1ConversationsConversationIdClearPostResult = AxiosResponse<MessageResponse>
export type DeleteConversationApiV1ConversationsConversationIdDeleteResult = AxiosResponse<MessageResponse>
export type PatchConversationApiV1ConversationsConversationIdPatchResult = AxiosResponse<ConversationResponse>
export type ListTurnsApiV1ConversationsConversationIdTurnsGetResult = AxiosResponse<TurnPageResponse>
export type AnalyzeApiV1ChatAnalyzePostResult = AxiosResponse<AnalyzeResponse>
export type StreamAnalyzeApiV1ChatStreamPostResult = AxiosResponse<unknown>
export type ResetEverythingApiV1AdminResetPostResult = AxiosResponse<MessageResponse>
export type TestGeminiApiKeyApiV1AdminTestGeminiPostResult = AxiosResponse<unknown>
export type GetWorkspacePathsApiV1WorkspacesWorkspaceIdPathsGetResult = AxiosResponse<WorkspacePathsResponse>
export type ExecuteWorkspaceCodeApiV1WorkspacesWorkspaceIdExecutePostResult = AxiosResponse<ExecuteResponse>
export type GetWorkspaceDatasetSchemaApiV1WorkspacesWorkspaceIdDatasetsTableNameSchemaGetResult = AxiosResponse<DatasetSchemaResponse>
export type SaveWorkspaceDatasetSchemaApiV1WorkspacesWorkspaceIdDatasetsTableNameSchemaPostResult = AxiosResponse<DatasetSchemaResponse>
export type GetWorkspaceDatasetPreviewApiV1WorkspacesWorkspaceIdDatasetsTableNamePreviewGetResult = AxiosResponse<DatasetPreviewResponse>
export type ListWorkspaceSchemasApiV1WorkspacesWorkspaceIdSchemasGetResult = AxiosResponse<SchemaListResponse>
export type RootGetResult = AxiosResponse<unknown>
