/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Inquira
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface ApiKeyRequest {
  /** Google Gemini API key */
  api_key: string;
}

export type ApiKeyResponseApiKey = string | null;

export interface ApiKeyResponse {
  api_key?: ApiKeyResponseApiKey;
}

export interface ChangePasswordRequest {
  /** @minLength 6 */
  current_password: string;
  /** @minLength 6 */
  new_password: string;
  /** @minLength 6 */
  confirm_password: string;
}

export type CheckUpdateResponseDataPath = string | null;

export type CheckUpdateResponseTableName = string | null;

export type CheckUpdateResponseDerivedTableName = string | null;

export type CheckUpdateResponseStoredSourceMtime = string | null;

export type CheckUpdateResponseCurrentSourceMtime = string | null;

export type CheckUpdateResponseStoredFileSize = number | null;

export type CheckUpdateResponseCurrentFileSize = number | null;

export type CheckUpdateResponseDatasetCreatedAt = string | null;

export type CheckUpdateResponseDatasetUpdatedAt = string | null;

export interface CheckUpdateResponse {
  success?: boolean;
  should_update: boolean;
  reasons: string[];
  data_path?: CheckUpdateResponseDataPath;
  file_exists?: boolean;
  table_name?: CheckUpdateResponseTableName;
  derived_table_name?: CheckUpdateResponseDerivedTableName;
  stored_source_mtime?: CheckUpdateResponseStoredSourceMtime;
  current_source_mtime?: CheckUpdateResponseCurrentSourceMtime;
  stored_file_size?: CheckUpdateResponseStoredFileSize;
  current_file_size?: CheckUpdateResponseCurrentFileSize;
  dataset_created_at?: CheckUpdateResponseDatasetCreatedAt;
  dataset_updated_at?: CheckUpdateResponseDatasetUpdatedAt;
}

export interface CodeExecutionRequest {
  /** Python code to execute */
  code: string;
}

/**
 * Execution result
 */
export type CodeExecutionResponseResult = unknown | null;

/**
 * Captured stdout output
 */
export type CodeExecutionResponseOutput = string | null;

/**
 * Error message if execution failed
 */
export type CodeExecutionResponseError = string | null;

export interface CodeExecutionResponse {
  /** Execution result */
  result?: CodeExecutionResponseResult;
  /** Captured stdout output */
  output?: CodeExecutionResponseOutput;
  /** Error message if execution failed */
  error?: CodeExecutionResponseError;
  /** Time taken to execute the code */
  execution_time: number;
}

/**
 * Execution result
 */
export type CodeExecutionWithVariablesResponseResult = unknown | null;

/**
 * Dictionary of variables created by the code
 */
export type CodeExecutionWithVariablesResponseVariables = { [key: string]: unknown };

/**
 * Captured stdout output
 */
export type CodeExecutionWithVariablesResponseOutput = string | null;

/**
 * Error message if execution failed
 */
export type CodeExecutionWithVariablesResponseError = string | null;

export interface CodeExecutionWithVariablesResponse {
  /** Execution result */
  result?: CodeExecutionWithVariablesResponseResult;
  /** Dictionary of variables created by the code */
  variables?: CodeExecutionWithVariablesResponseVariables;
  /** Captured stdout output */
  output?: CodeExecutionWithVariablesResponseOutput;
  /** Error message if execution failed */
  error?: CodeExecutionWithVariablesResponseError;
  /** Time taken to execute the code */
  execution_time: number;
}

export interface ContextRequest {
  /** Context about the data domain */
  context: string;
}

export type ContextResponseContext = string | null;

export interface ContextResponse {
  context?: ContextResponseContext;
}

/**
 * Additional context about the data
 */
export type DataAnalysisRequestContext = string | null;

export interface DataAnalysisRequest {
  /** current python code which will be used to guide LLM to generate new code */
  current_code?: string;
  /** The question to ask about the data */
  question: string;
  /** The LLM model to use */
  model?: string;
  /** Additional context about the data */
  context?: DataAnalysisRequestContext;
}

export interface DataAnalysisResponse {
  /** Whether the query is safe to execute */
  is_safe: boolean;
  /** Whether the query is relevant to data analysis */
  is_relevant: boolean;
  /** Generated Python code for the analysis */
  code: string;
  /** Explanation of the analysis in markdown format */
  explanation: string;
}

export interface DataPathRequest {
  /** Path to the data file */
  data_path: string;
}

export type DataPathResponseDataPath = string | null;

export interface DataPathResponse {
  data_path?: DataPathResponseDataPath;
}

/**
 * Path to the generated per-file schema JSON
 */
export type DatasetInfoSchemaPath = string | null;

/**
 * Size of the file in bytes
 */
export type DatasetInfoFileSize = number | null;

/**
 * Last modification time of the file (seconds since epoch)
 */
export type DatasetInfoSourceMtime = number | null;

export type DatasetInfoCreatedAt = string | null;

export type DatasetInfoUpdatedAt = string | null;

export interface DatasetInfo {
  /** Original absolute path to the data file */
  data_path: string;
  /** Stable DuckDB table name used for this file */
  table_name: string;
  /** Path to the generated per-file schema JSON */
  schema_path?: DatasetInfoSchemaPath;
  /** Computed fingerprint for this file/version */
  file_hash: string;
  /** Size of the file in bytes */
  file_size?: DatasetInfoFileSize;
  /** Last modification time of the file (seconds since epoch) */
  source_mtime?: DatasetInfoSourceMtime;
  created_at?: DatasetInfoCreatedAt;
  updated_at?: DatasetInfoUpdatedAt;
}

export interface DeleteAccountRequest {
  /** Must be 'DELETE' to confirm account deletion */
  confirmation_text: string;
  /**
   * Current password for verification
   * @minLength 6
   */
  current_password: string;
}

export interface GeminiTestRequest {
  /** Google Gemini API key to test */
  api_key: string;
}

/**
 * optional context override
 */
export type GenerateSchemaRequestContext = string | null;

export interface GenerateSchemaRequest {
  /** filepath where the data is stored */
  filepath: string;
  /** optional context override */
  context?: GenerateSchemaRequestContext;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PathsResponse {
  schema_path: string;
  database_path: string;
  base_directory: string;
}

export type SampleType = typeof SampleType[keyof typeof SampleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SampleType = {
  random: 'random',
  first: 'first',
} as const;

export interface SaveSchemaRequest {
  filepath: string;
  context: string;
  columns: SchemaColumnResponse[];
}

export interface SchemaColumnResponse {
  name: string;
  description: string;
  data_type: string;
  sample_values: unknown[];
}

export type SettingsResponseDataPath = string | null;

export type SettingsResponseContext = string | null;

export type SettingsResponseSettingsCreatedAt = string | null;

export type SettingsResponseSettingsUpdatedAt = string | null;

export type SettingsResponseBaseDirectory = string | null;

export type SettingsResponseSchemaPath = string | null;

export type SettingsResponseDatabasePath = string | null;

export type SettingsResponseFileSizeBytes = number | null;

export type SettingsResponseFileMtime = string | null;

export type SettingsResponseFileCtime = string | null;

export type SettingsResponseTableName = string | null;

export type SettingsResponseDatasetCreatedAt = string | null;

export type SettingsResponseDatasetUpdatedAt = string | null;

export type SettingsResponseDerivedTableName = string | null;

export interface SettingsResponse {
  data_path?: SettingsResponseDataPath;
  context?: SettingsResponseContext;
  api_key_present?: boolean;
  settings_created_at?: SettingsResponseSettingsCreatedAt;
  settings_updated_at?: SettingsResponseSettingsUpdatedAt;
  base_directory?: SettingsResponseBaseDirectory;
  schema_path?: SettingsResponseSchemaPath;
  database_path?: SettingsResponseDatabasePath;
  file_exists?: boolean;
  file_size_bytes?: SettingsResponseFileSizeBytes;
  file_mtime?: SettingsResponseFileMtime;
  file_ctime?: SettingsResponseFileCtime;
  table_name?: SettingsResponseTableName;
  dataset_created_at?: SettingsResponseDatasetCreatedAt;
  dataset_updated_at?: SettingsResponseDatasetUpdatedAt;
  derived_table_name?: SettingsResponseDerivedTableName;
}

export interface UserLoginRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** @minLength 6 */
  password: string;
}

export interface UserRegisterRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** @minLength 6 */
  password: string;
}

export interface UserResponse {
  user_id: string;
  username: string;
  created_at: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetDataSchemaDataSchemaGet200 = { [key: string]: unknown };

export type GetDataPreviewDataPreviewGetParams = {
sample_type?: SampleType;
};

export type GetDataPreviewDataPreviewGet200 = { [key: string]: unknown };

export type RefreshDataPreviewDataPreviewRefreshPostParams = {
sample_type?: SampleType;
};

export type RefreshDataPreviewDataPreviewRefreshPost200 = { [key: string]: unknown };

export type ClearPreviewCacheDataPreviewCacheDelete200 = { [key: string]: unknown };

export type GenerateSchemaSchemasGeneratePostParams = {
model?: string;
};

export type GetSessionVariablesExecuteSessionVariablesGet200 = { [key: string]: unknown };

export type LookupDatasetDatasetsLookupGetParams = {
/**
 * Absolute path to the data file
 */
data_path: string;
};

export const getInquira = () => {
/**
 * Register a new user
 * @summary Register User
 */
const registerUserAuthRegisterPost = <TData = AxiosResponse<UserResponse>>(
    userRegisterRequest: UserRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register`,
      userRegisterRequest,options
    );
  }

/**
 * Login user and create session
 * @summary Login User
 */
const loginUserAuthLoginPost = <TData = AxiosResponse<unknown>>(
    userLoginRequest: UserLoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      userLoginRequest,options
    );
  }

/**
 * Logout user by clearing session
 * @summary Logout User
 */
const logoutUserAuthLogoutPost = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/logout`,undefined,options
    );
  }

/**
 * Verify if user is authenticated
 * @summary Verify Auth
 */
const verifyAuthAuthVerifyGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/auth/verify`,options
    );
  }

/**
 * Get user profile
 * @summary Get User Profile
 */
const getUserProfileAuthProfileGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/auth/profile`,options
    );
  }

/**
 * Change user password
 * @summary Change Password
 */
const changePasswordAuthChangePasswordPost = <TData = AxiosResponse<unknown>>(
    changePasswordRequest: ChangePasswordRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/change-password`,
      changePasswordRequest,options
    );
  }

/**
 * Delete user account permanently with confirmation
 * @summary Delete Account
 */
const deleteAccountAuthDeleteAccountDelete = <TData = AxiosResponse<unknown>>(
    deleteAccountRequest: DeleteAccountRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/auth/delete-account`,{data:
      deleteAccountRequest, ...options}
    );
  }

/**
 * Data analysis chat endpoint that returns structured response with code and explanation
 * @summary Chat Endpoint
 */
const chatEndpointChatPost = <TData = AxiosResponse<DataAnalysisResponse>>(
    dataAnalysisRequest: DataAnalysisRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/chat`,
      dataAnalysisRequest,options
    );
  }

/**
 * Get chat history for the current user and active data file.
 * @summary Get Chat History
 */
const getChatHistoryHistoryGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/history`,options
    );
  }

/**
 * Set the data file path and start background processing with WebSocket updates
 * @summary Set Data Path
 */
const setDataPathSettingsSetDataPathPut = <TData = AxiosResponse<unknown>>(
    dataPathRequest: DataPathRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/settings/set/data_path`,
      dataPathRequest,options
    );
  }

/**
 * Set the context for schema generation
 * @summary Set Context
 */
const setContextSettingsSetContextPut = <TData = AxiosResponse<unknown>>(
    contextRequest: ContextRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/settings/set/context`,
      contextRequest,options
    );
  }

/**
 * Set the data file path without triggering processing (simple update only)
 * @summary Set Data Path Simple
 */
const setDataPathSimpleSettingsSetDataPathSimplePut = <TData = AxiosResponse<unknown>>(
    dataPathRequest: DataPathRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/settings/set/data_path_simple`,
      dataPathRequest,options
    );
  }

/**
 * Set the API key
 * @summary Set Apikey
 */
const setApikeySettingsSetApiKeyPut = <TData = AxiosResponse<unknown>>(
    apiKeyRequest: ApiKeyRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/settings/set/api_key`,
      apiKeyRequest,options
    );
  }

/**
 * View the current data file path
 * @summary View Data Path
 */
const viewDataPathSettingsViewDataPathGet = <TData = AxiosResponse<DataPathResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/settings/view/data_path`,options
    );
  }

/**
 * View the current context
 * @summary View Context
 */
const viewContextSettingsViewContextGet = <TData = AxiosResponse<ContextResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/settings/view/context`,options
    );
  }

/**
 * View the current API key
 * @summary View Apikey
 */
const viewApikeySettingsViewApiKeyGet = <TData = AxiosResponse<ApiKeyResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/settings/view/api_key`,options
    );
  }

/**
 * View all settings
 * @summary View All Settings
 */
const viewAllSettingsSettingsViewGet = <TData = AxiosResponse<SettingsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/settings/view`,options
    );
  }

/**
 * Get the paths where schema and database files are stored
 * @summary Get Storage Paths
 */
const getStoragePathsSettingsPathsGet = <TData = AxiosResponse<PathsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/settings/paths`,options
    );
  }

/**
 * Return whether the DuckDB table needs to be updated and why.

Compares current filesystem metadata with the stored dataset catalog.
Does not perform any update.
 * @summary Check Update Needed
 */
const checkUpdateNeededSettingsCheckUpdateGet = <TData = AxiosResponse<CheckUpdateResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/settings/check-update`,options
    );
  }

/**
 * Temporarily close database connections to allow external access
 * @summary Close Database Connections
 */
const closeDatabaseConnectionsSettingsCloseConnectionsPost = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/settings/close-connections`,undefined,options
    );
  }

/**
 * Get schema information for the user's data file
First checks for existing saved schema, falls back to generating new one if needed
 * @summary Get Data Schema
 */
const getDataSchemaDataSchemaGet = <TData = AxiosResponse<GetDataSchemaDataSchemaGet200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/data/schema`,options
    );
  }

/**
 * Get a preview of the user's data file with different sampling options

Returns cached data if available, otherwise generates new preview.
 * @summary Get Data Preview
 */
const getDataPreviewDataPreviewGet = <TData = AxiosResponse<GetDataPreviewDataPreviewGet200>>(
    params?: GetDataPreviewDataPreviewGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/data/preview`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Refresh the cached preview data for the user's data file

Forces regeneration of preview data and updates the cache.
 * @summary Refresh Data Preview
 */
const refreshDataPreviewDataPreviewRefreshPost = <TData = AxiosResponse<RefreshDataPreviewDataPreviewRefreshPost200>>(
    params?: RefreshDataPreviewDataPreviewRefreshPostParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/data/preview/refresh`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Clear all cached preview data for the current user
 * @summary Clear Preview Cache
 */
const clearPreviewCacheDataPreviewCacheDelete = <TData = AxiosResponse<ClearPreviewCacheDataPreviewCacheDelete200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/data/preview/cache`,options
    );
  }

/**
 * @summary Generate Schema
 */
const generateSchemaSchemasGeneratePost = <TData = AxiosResponse<unknown>>(
    generateSchemaRequest: GenerateSchemaRequest,
    params?: GenerateSchemaSchemasGeneratePostParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/schemas/generate`,
      generateSchemaRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Load an existing schema for a data file.

If no schema exists yet, attempt to generate a minimal schema (without LLM)
based on DuckDB DESCRIBE and sample values, then save and return it.
 * @summary Load Schema Endpoint
 */
const loadSchemaEndpointSchemasLoadFilepathGet = <TData = AxiosResponse<unknown>>(
    filepath: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/schemas/load/${filepath}`,options
    );
  }

/**
 * Save a user-modified schema
 * @summary Save Schema Endpoint
 */
const saveSchemaEndpointSchemasSavePost = <TData = AxiosResponse<unknown>>(
    saveSchemaRequest: SaveSchemaRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/schemas/save`,
      saveSchemaRequest,options
    );
  }

/**
 * List all schemas for the current user
 * @summary List Schemas Endpoint
 */
const listSchemasEndpointSchemasListGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/schemas/list`,options
    );
  }

/**
 * Execute Python code

This endpoint:
- Executes code in the environment
- Returns results or error messages
 * @summary Execute Code
 */
const executeCodeExecutePost = <TData = AxiosResponse<CodeExecutionResponse>>(
    codeExecutionRequest: CodeExecutionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/execute/`,
      codeExecutionRequest,options
    );
  }

/**
 * Get current session variables for debugging purposes

Returns:
    Dictionary containing global and local variables in the user's session
 * @summary Get Session Variables
 */
const getSessionVariablesExecuteSessionVariablesGet = <TData = AxiosResponse<GetSessionVariablesExecuteSessionVariablesGet200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/execute/session-variables`,options
    );
  }

/**
 * Clear all session variables for the current user
 * @summary Clear Session Variables
 */
const clearSessionVariablesExecuteSessionVariablesDelete = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/execute/session-variables`,options
    );
  }

/**
 * Execute Python code and return created variables

This endpoint:
- Executes the code in the environment
- Extracts and returns the variables created by the code
- Returns results, variables, or error messages
 * @summary Execute Code With Variables
 */
const executeCodeWithVariablesExecuteWithVariablesPost = <TData = AxiosResponse<CodeExecutionWithVariablesResponse>>(
    codeExecutionRequest: CodeExecutionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/execute/with-variables`,
      codeExecutionRequest,options
    );
  }

/**
 * Test a Google Gemini API key by making a simple test request.

This endpoint validates that the provided API key is working
by sending a simple test message to Gemini.

Returns:
- 200 OK: API key is valid
- 400 Bad Request: Missing or empty API key
- 401 Unauthorized: Invalid API key
- 403 Forbidden: Insufficient permissions
- 429 Too Many Requests: Quota exceeded
- 500 Internal Server Error: Other errors
 * @summary Test Gemini Api Key
 */
const testGeminiApiKeyApiTestGeminiPost = <TData = AxiosResponse<unknown>>(
    geminiTestRequest: GeminiTestRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/test-gemini`,
      geminiTestRequest,options
    );
  }

/**
 * Return dataset info (table_name, schema_path, etc.) for the given data_path
 * @summary Lookup Dataset
 */
const lookupDatasetDatasetsLookupGet = <TData = AxiosResponse<DatasetInfo>>(
    params: LookupDatasetDatasetsLookupGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/datasets/lookup`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * List all datasets for the current user
 * @summary List User Datasets
 */
const listUserDatasetsDatasetsListGet = <TData = AxiosResponse<DatasetInfo[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/datasets/list`,options
    );
  }

/**
 * Open a native OS file dialog on the local machine and return the absolute path.

Safety/Scope:
- Controlled by the CLI flag `--no-file-dialog` (default: enabled). Set env `INQUIRA_ALLOW_FILE_DIALOG=0` to disable when running in embedded contexts.
- Only accepts requests from localhost (127.0.0.1/::1).
- No file content is uploaded; only the absolute path string is returned.
 * @summary Open File Dialog
 */
const openFileDialogSystemOpenFileDialogPost = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/system/open-file-dialog`,undefined,options
    );
  }

/**
 * Return the Terms & Conditions as Markdown text.

Media type is `text/markdown` so browser/clients can render or display
it appropriately. The content is packaged with the application under
`inquira/legal/terms.md`.
 * @summary Terms & Conditions (Markdown)
 */
const getTermsMarkdownLegalTermsGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/legal/terms`,options
    );
  }

/**
 * Root endpoint to check if API is running
 * @summary Root
 */
const rootGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

return {registerUserAuthRegisterPost,loginUserAuthLoginPost,logoutUserAuthLogoutPost,verifyAuthAuthVerifyGet,getUserProfileAuthProfileGet,changePasswordAuthChangePasswordPost,deleteAccountAuthDeleteAccountDelete,chatEndpointChatPost,getChatHistoryHistoryGet,setDataPathSettingsSetDataPathPut,setContextSettingsSetContextPut,setDataPathSimpleSettingsSetDataPathSimplePut,setApikeySettingsSetApiKeyPut,viewDataPathSettingsViewDataPathGet,viewContextSettingsViewContextGet,viewApikeySettingsViewApiKeyGet,viewAllSettingsSettingsViewGet,getStoragePathsSettingsPathsGet,checkUpdateNeededSettingsCheckUpdateGet,closeDatabaseConnectionsSettingsCloseConnectionsPost,getDataSchemaDataSchemaGet,getDataPreviewDataPreviewGet,refreshDataPreviewDataPreviewRefreshPost,clearPreviewCacheDataPreviewCacheDelete,generateSchemaSchemasGeneratePost,loadSchemaEndpointSchemasLoadFilepathGet,saveSchemaEndpointSchemasSavePost,listSchemasEndpointSchemasListGet,executeCodeExecutePost,getSessionVariablesExecuteSessionVariablesGet,clearSessionVariablesExecuteSessionVariablesDelete,executeCodeWithVariablesExecuteWithVariablesPost,testGeminiApiKeyApiTestGeminiPost,lookupDatasetDatasetsLookupGet,listUserDatasetsDatasetsListGet,openFileDialogSystemOpenFileDialogPost,getTermsMarkdownLegalTermsGet,rootGet}};
export type RegisterUserAuthRegisterPostResult = AxiosResponse<UserResponse>
export type LoginUserAuthLoginPostResult = AxiosResponse<unknown>
export type LogoutUserAuthLogoutPostResult = AxiosResponse<unknown>
export type VerifyAuthAuthVerifyGetResult = AxiosResponse<unknown>
export type GetUserProfileAuthProfileGetResult = AxiosResponse<unknown>
export type ChangePasswordAuthChangePasswordPostResult = AxiosResponse<unknown>
export type DeleteAccountAuthDeleteAccountDeleteResult = AxiosResponse<unknown>
export type ChatEndpointChatPostResult = AxiosResponse<DataAnalysisResponse>
export type GetChatHistoryHistoryGetResult = AxiosResponse<unknown>
export type SetDataPathSettingsSetDataPathPutResult = AxiosResponse<unknown>
export type SetContextSettingsSetContextPutResult = AxiosResponse<unknown>
export type SetDataPathSimpleSettingsSetDataPathSimplePutResult = AxiosResponse<unknown>
export type SetApikeySettingsSetApiKeyPutResult = AxiosResponse<unknown>
export type ViewDataPathSettingsViewDataPathGetResult = AxiosResponse<DataPathResponse>
export type ViewContextSettingsViewContextGetResult = AxiosResponse<ContextResponse>
export type ViewApikeySettingsViewApiKeyGetResult = AxiosResponse<ApiKeyResponse>
export type ViewAllSettingsSettingsViewGetResult = AxiosResponse<SettingsResponse>
export type GetStoragePathsSettingsPathsGetResult = AxiosResponse<PathsResponse>
export type CheckUpdateNeededSettingsCheckUpdateGetResult = AxiosResponse<CheckUpdateResponse>
export type CloseDatabaseConnectionsSettingsCloseConnectionsPostResult = AxiosResponse<unknown>
export type GetDataSchemaDataSchemaGetResult = AxiosResponse<GetDataSchemaDataSchemaGet200>
export type GetDataPreviewDataPreviewGetResult = AxiosResponse<GetDataPreviewDataPreviewGet200>
export type RefreshDataPreviewDataPreviewRefreshPostResult = AxiosResponse<RefreshDataPreviewDataPreviewRefreshPost200>
export type ClearPreviewCacheDataPreviewCacheDeleteResult = AxiosResponse<ClearPreviewCacheDataPreviewCacheDelete200>
export type GenerateSchemaSchemasGeneratePostResult = AxiosResponse<unknown>
export type LoadSchemaEndpointSchemasLoadFilepathGetResult = AxiosResponse<unknown>
export type SaveSchemaEndpointSchemasSavePostResult = AxiosResponse<unknown>
export type ListSchemasEndpointSchemasListGetResult = AxiosResponse<unknown>
export type ExecuteCodeExecutePostResult = AxiosResponse<CodeExecutionResponse>
export type GetSessionVariablesExecuteSessionVariablesGetResult = AxiosResponse<GetSessionVariablesExecuteSessionVariablesGet200>
export type ClearSessionVariablesExecuteSessionVariablesDeleteResult = AxiosResponse<unknown>
export type ExecuteCodeWithVariablesExecuteWithVariablesPostResult = AxiosResponse<CodeExecutionWithVariablesResponse>
export type TestGeminiApiKeyApiTestGeminiPostResult = AxiosResponse<unknown>
export type LookupDatasetDatasetsLookupGetResult = AxiosResponse<DatasetInfo>
export type ListUserDatasetsDatasetsListGetResult = AxiosResponse<DatasetInfo[]>
export type OpenFileDialogSystemOpenFileDialogPostResult = AxiosResponse<unknown>
export type GetTermsMarkdownLegalTermsGetResult = AxiosResponse<unknown>
export type RootGetResult = AxiosResponse<unknown>
